# Generated by Django 5.2 on 2025-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='description',
            field=models.CharField(),
        ),
    ]
